### ISSUE TITLE
IndexOutOfBoundsException: 0 in Time Entry

### ISSUE THREAD

**Issue by drytoastman** [drytoastman/wwscc#47]
Basic error below that Dan keeps seeing.

```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
    at java.util.Vector.get(Unknown Source)
    at org.wwscc.dataentry.SimpleTimeListModel.getElementAt(SimpleTimeListModel.java:76)
    at org.wwscc.dataentry.SimpleTimeListModel.getElementAt(SimpleTimeListModel.java:22)
    at javax.swing.JList.getSelectedValue(Unknown Source)
    at org.wwscc.dataentry.TimeEntry.valueChanged(TimeEntry.java:610)
```

**Comment by drytoastman** [comment]
Bizzare.  General processing is:

1. Enter time is selected
2. Time is removed from the data model and fireIntervalRemoved is called
3. Event propagation causes a change in the JList selected value model
4. This calls back into our code as valueChanged()
5. In value changed, we call getSelectedValue()
6. The JList implementation is calling getElementAt(0) which means that the SelectionModel still thinks something is selected even though we just removed it.

Since I can't reproduce and everything happens in the event dispatch thread, I'm assuming this was a JDK bug.
